#!/bin/bash
set -e

CMD=$1
shift

echo "running $CMD task command"

exe() { echo "$@" ; $@ ; }

case $CMD in
  clean)
    echo "The current working directory: $PWD"
    exe "rm -rf node_modules"
    exe "rm -rf package-lock.json"
    exe "rm -rf lib"
    ;;

  compile)
    exe "../../node_modules/.bin/babel --config-file $(pwd)/babel.config.js --verbose -d ./lib ./src --ignore ./src/**/__tests__/,./src/**/__stories__/"
    ;;

  test)
    #if [ -d "./**/__tests__" ]; then
      exe "../../node_modules/.bin/jest -c $(pwd)/jest.config.js --rootDir ."
    #else
      #echo "No tests to run"
    #fi
    ;;

  lint)
    exe "../../node_modules/.bin/eslint ./src -c $(pwd)/eslint.config.js --report-unused-disable-directives"
    ;;

  *)
    if [[ -z "$CMD" ]]; then
      echo "USAGE: ./task (clean|compile|test|lint|<node_modules_bin_command>) command_args"
      exit 0
    fi
    exe "../../node_modules/.bin/$CMD $@"
    ;;
esac